const errors = {
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  USER_OR_PASSWORD_WRONG: "USER_OR_PASSWORD_WRONG",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATA_VALIDATION_ERROR: "DATA_VALIDATION_ERROR",
  PARAMS_MISSED: "PARAMS_MISSED"
};
module.exports = errors;
